server:
  port: 8020
spring:
  application:
    name: machine-hy-envoy
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.200.174:3306/creatorcloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.200.174:8848
        #ip: 124.70.200.174
      config:
        file-extension: yaml
        group: machinePlatform
        server-addr: 124.70.200.174:8848

# redisson lock
redisson.address: redis://localhost:6379